config/routes.rb
Rails.application.routes.draw do
  # App Paths
  root to: "dashboard#index"

  # GraphQL
  post "/graphql", to: "graphql#execute"
  mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql" if Rails.env.development?

  # Devise Setup
  devise_scope :user do
    get "users/sign_out" => "devise/sessions#destroy"
  end

  devise_for :users, path: "users"

  namespace :admin do
    resources :organizations, only: [:show, :edit, :update]
    resources :admin_users, except: :destroy do
      member do
        patch "activate"
        patch "deactivate"
      end
    end

    resources :volunteers, except: :destroy do
      member do
        patch "activate"
        patch "deactivate"
        post :send_link
      end
    end

    resources :students, except: :destroy do
      member do
        get :activate
        get :deactivate
      end
    end

    resources :tickets, except: :destroy do
      member do
        post :resolve
      end
    end

    resources :surveys, except: :destroy do
      member do
        post :resolve
      end
    end

    match "imports/volunteers", to: "imports#volunteers", via: :post
    match "imports/students", to: "imports#students", via: :post
  end
end

app/models/student.rb
class Student < ApplicationRecord
  include ExportToCsv
  include MeetingDurations

  EXPORT_HEADERS = ["First Name", "Last Name", "Volunteer Name(s)", "Staff Contact", "DOB", "Guardian First Name",
    "Guardian Last Name", "Guardian Email", "Guardian Phone", "Emergency Contact First Name",
    "Emergency Contact Last Name", "Emergency Contact Phone", "Hours logged", "Number of sessions",
    "City", "State"].freeze

  EXPORT_COLUMNS = %w[first_name last_name volunteer_names_for_csv staff.name
    date_of_birth guardian_first_name guardian_last_name
    guardian_email guardian_phone_number emergency_contact_first_name emergency_contact_last_name
    emergency_contact_phone_number hours_logged completed_responses.count city state].freeze

  has_many :student_volunteer_assignments
  has_many :active_student_volunteer_assignments, lambda {
                                                    where("student_volunteer_assignments.end_date > ?", Date.current)
                                                  }, class_name: "StudentVolunteerAssignment"
  has_many :volunteers, through: :active_student_volunteer_assignments

  has_many :student_staff_assignments
  has_one :active_student_staff_assignment, lambda {
                                              where("student_staff_assignments.end_date > ?", Date.current)
                                            }, class_name: "StudentStaffAssignment"
  has_one :staff, through: :active_student_staff_assignment

  belongs_to :deactivator, class_name: "User", optional: true

  validates :first_name, :last_name, :phone_number, presence: true
  validates :state, length: {minimum: 2, maximum: 2}, allow_blank: true
  validates :phone_number, format: { with: /\A\d{10}\z/ , message: "must be valid." }

  enum status: {active: 0, inactive: 1}

  def update_with_assignments!(student_attributes:, staff_id:, volunteer_ids: [])
    transaction do
      update_staff_assignment(staff_id.to_s)
      update_volunteer_assignments(volunteer_ids: volunteer_ids)
      update(student_attributes)
    end
  end

  def name
    "#{first_name} #{last_name}"
  end

  def guardian_name
    "#{guardian_last_name}, #{guardian_first_name}"
  end

  def initials
    first_name[0] + last_name[0]
  end

  def deactivate!(deactivator_id:)
    self.deactivated_at = Time.now
    self.deactivator_id = deactivator_id
    self.status = :inactive
    save!
  end

  def activate!
    self.status = :active
    save!
  end

  def volunteer_names_for_csv
    volunteers.map(&:name).join("/")
  end

  private

  def update_volunteer_assignments(volunteer_ids: [])
    active_volunteer_ids = active_student_volunteer_assignments.pluck(:volunteer_id).map(&:to_s).sort || []
    volunteer_ids ||= []

    return if active_volunteer_ids == volunteer_ids&.sort

    volunteer_ids.compact_blank!

    inactive_ids = active_volunteer_ids - volunteer_ids
    if inactive_ids.present?
      active_student_volunteer_assignments.where(volunteer_id: inactive_ids).update(end_date: Date.current)
    end

    new_volunteers = volunteer_ids - active_volunteer_ids
    new_volunteers.each do |volunteer_id|
      StudentVolunteerAssignment.create!(student: self, volunteer_id: volunteer_id, start_date: Date.current)
    end
  end

  def update_staff_assignment(staff_id)
    if active_student_staff_assignment.present? &&
        active_student_staff_assignment.staff_id.to_s != staff_id
      active_student_staff_assignment.update!(end_date: Date.current)
      StudentStaffAssignment.create!(student: self, staff_id: staff_id, start_date: Date.current) if staff_id.present?
    elsif active_student_staff_assignment.blank?
      StudentStaffAssignment.create!(student: self, staff_id: staff_id, start_date: Date.current) if staff_id.present?
    end
  end
end

app/controllers/admin/students_controller.rb
module Admin
  class StudentsController < ApplicationController
    include Carmen

    def index
      @nav = "Students"
      @total_students = Student.order(:last_name)
      @pagy, @students = pagy(@total_students)

      respond_to do |format|
        format.html
        format.csv do
          send_data Student.export_to_csv(@total_students,
            columns: Student::EXPORT_COLUMNS,
            headers: Student::EXPORT_HEADERS),
            filename: "students-#{Date.today}.csv"
        end
      end
    end

    def new
      @student = Student.new
    end

    def edit
      @student = Student.find(params[:id])
    end

    def create
      @student = Student.new(students_params)

      if @student.valid?
        @student.save!
        redirect_to admin_students_url, notice: "Student was successfully created."
      else
        flash[:alert] = format_errors(@student)
        render :new
      end
    end

    def update
      @student = Student.find(params[:id])

      if @student.update_with_assignments!(
        student_attributes: students_params.except(:volunteer_ids),
        volunteer_ids: params[:student][:volunteer_ids],
        staff_id: params[:student][:staff_id]
      )
        redirect_to admin_students_url, notice: "Student was successfully updated."
      else
        flash[:alert] = format_errors(@student)
        render :edit
      end
    end

    def activate
      @student = Student.find(params[:id])
      @student.activate!

      redirect_to admin_students_url, notice: "Student was successfully activated."
    end

    def deactivate
      @student = Student.find(params[:id])

      @student.deactivate!(deactivator_id: current_user.id)

      redirect_to admin_students_url, notice: "Student was successfully deactivated."
    end

    def students_params
      params.require(:student).permit(:first_name, :last_name,
        :email, :phone_number, :guardian_phone_number, :guardian_email, :guardian_first_name,
        :guardian_last_name, :emergency_contact_first_name, :emergency_contact_last_name,
        :emergency_contact_phone_number, :date_of_birth, :city, :state, volunteer_ids: [])
    end
  end
end

app/views/admin/students/_form.html.erb
<%= form_with(model: @student, url: path) do |form| %>
  <div class="row pr-3 pb-4">
    <div class="col-3">
      <%= form.text_field :first_name, class: "form-control", placeholder: "First Name" %>
    </div>

    <div class="col-3">
      <%= form.text_field :last_name, class: "form-control", placeholder: "Last Name" %>
    </div>
  </div>

  <div class="row pr-3 pb-4">
    <div class="col-6">
      <%= form.text_field :date_of_birth, class: "form-control", placeholder: "Date of Birth" %>
    </div>
  </div>

  <div class="row pr-3 pb-4">
    <div class="col-6">
      <%= form.text_field :email, class: "form-control", placeholder: "Email" %>
    </div>
  </div>

  <div class="row pr-3 pb-4">
    <div class="col-6">
      <%= form.text_field :phone_number, class: "form-control", placeholder: "Phone Number" %>
    </div>
  </div>

  <div class="row pr-3 pb-4">
    <div class="col-3">
      <%= form.text_field :guardian_first_name, class: "form-control", placeholder: "Guardian First Name" %>
    </div>

    <div class="col-3">
      <%= form.text_field :guardian_last_name, class: "form-control", placeholder: "Guardian Last Name" %>
    </div>
  </div>

  <div class="row pr-3 pb-4">
    <div class="col-6">
      <%= form.text_field :guardian_email, class: "form-control", placeholder: "Guardian Email" %>
    </div>
  </div>

  <div class="row pr-3 pb-4">
    <div class="col-6">
      <%= form.text_field :guardian_phone_number, class: "form-control", placeholder: "Guardian Phone Number" %>
    </div>
  </div>

  <div class="row pr-3 pb-4">
    <div class="col-3">
      <%= form.text_field :emergency_contact_first_name, class: "form-control", placeholder: "Emergency Contact First Name" %>
    </div>

    <div class="col-3">
      <%= form.text_field :emergency_contact_last_name, class: "form-control", placeholder: "Emergency Contact Last Name" %>
    </div>
  </div>

  <div class="row pr-3 pb-4">
    <div class="col-6">
      <%= form.text_field :emergency_contact_phone_number, class: "form-control", placeholder: "Emergency Contact Phone Number" %>
    </div>
  </div>

  <div class="row pr-3 pb-4">
    <div class="col-3">
      <%= form.text_field :city, class: "form-control", placeholder: "City" %>
    </div>

    <div class="col-3">
      <%= form.select(
        :state,
        Carmen::Country.coded("US").subregions.typed("state").map { |state| [state.name, state.code] },
        { include_hidden: false, selected: @student.state },
        { 'data-controller' => 'autocomplete-select',
          'data-autocomplete-select-placeholder' => "Select State" }
      ) %>
    </div>
  </div>

  <label class="text-dark-gray mt-4 mb-1">ASSIGN VOLUNTEER</label>
  <div class="row pr-3 pb-4">
    <div class="col-6">
      <%= form.select(
        :volunteer_ids,
        User.where(role: :volunteer, status: :active).map { |volunteer| [volunteer.name, volunteer.id] },
        { include_hidden: false, selected: @student.active_student_volunteer_assignments.map(&:volunteer_id) },
        { 'data-controller' => 'autocomplete-select',
          'data-autocomplete-select-placeholder' => "Select Volunteer",
          multiple: true }
      ) %>
    </div>
  </div>

  <label class="text-dark-gray mt-4 mb-1">ASSIGN STAFF CONTACT</label>
  <div class="row pr-3 pb-4">
    <div class="col-6">
      <%= form.select(
        :staff_id,
        User.where(role: :admin).map { |staff| [staff.name, staff.id] },
        { include_hidden: false, selected: @student.active_student_staff_assignment&.staff_id },
        { 'data-controller' => 'autocomplete-select',
          'data-autocomplete-select-placeholder' => "Select Staff" }
      ) %>
    </div>
  </div>

  <div class="row pr-3 pb-4 mt-4">
    <div class="col-2">
      <%= link_to "CANCEL", admin_students_path, class: "btn btn-lg btn-purple-secondary" %>
    </div>
    <div class="col-2">
      <%= form.submit "SAVE", class: "btn btn-lg btn-purple-primary" %>
    </div>
  </div>
<% end %>

app/views/admin/students/_students_table.html.erb
<table id="sortable">
  <thead>
    <tr>
      <th
        id="students-first-name"
        data-reflex="click->StudentsTable#sort"
        data-column="first_name"
        data-direction="asc"
        scope="col"
        class="hover:cursor-pointer"
      >
        <span>First Name</span>
      </th>
      <th
        id="students-last-name"
        data-reflex="click->StudentsTable#sort"
        data-column="last_name"
        data-direction="asc"
        scope="col"
        class="hover:cursor-pointer"
      >
        <span>Last Name</span>
      </th>
      <th scope="col">Volunteers</th>
      <th scope="col">Staff Contact</th>
      <th
        id="guardian-name"
        data-reflex="click->StudentsTable#sort"
        data-column="guardian_last_name"
        data-direction="asc"
        scope="col"
        class="hover:cursor-pointer"
      >
        <span>Guardian Name</span>
      </th>
      <th scope="col">DOB</th>
      <th
        id="student-status"
        data-reflex="click->StudentsTable#sort"
        data-column="status"
        data-direction="asc"
        scope="col"
        class="hover:cursor-pointer"
      >
        <span>Status</span>
      </th>
      <th class="text-center" scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% records.each do |student| %>
      <tr scope="row">
        <td>
          <%= student.first_name %>
        </td>
        <td>
          <%= student.last_name %>
        </td>
        <td>
          <%= student.volunteers.map(&:name).join(", ") %>
        </td>
        <td>
          <%= student.staff&.name %>
        </td>
        <td>
          <%= student.guardian_name %>
        </td>
        <td>
          <%= student.date_of_birth&.strftime("%m/%d/%Y") %>
        </td>
        <td>
          <%= student.status %>
        </td>
        <td class="text-center text-teal">
          <%= link_to "Edit", edit_admin_student_path(student) %> |
          <% if student.status == "active" %>
            <%= link_to "Deactivate", deactivate_admin_student_path(student),
                data: {
                  confirm_swal: "Are you sure?",
                  confirm_text: "DEACTIVATE",
                  text: "This action will deactivate this student. Are you sure you want to proceed with deactivation?"
                }
             %>
          <% else %>
            <%= link_to "Activate", activate_admin_student_path(student),
                data: {
                  confirm_swal: "Are you sure?",
                  confirm_text: "ACTIVATE",
                  text: "This action will activate this student. Are you sure you want to proceed with activation?"
                }
            %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/students/edit.html.erb
<div class="m-5 container">
  <%= link_to "Back", admin_students_path %>

  <h2 class="my-4 mr-5">Edit Student</h2>

  <%= render "form", path: admin_student_url %>
</div>

app/views/admin/students/index.html.erb
<% content_for(:title) do %>
  Students
<% end %>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-2">
      <h1><%= page_header_title %></h1>
    </div>
    <div class="col-md-2 offset-md-8">
      <%= link_to "ADD NEW", new_admin_student_path, class: "btn btn-purple-primary" %>
    </div>
  </div>

  <div class="row mt-3 py-3 bg-white">
    <div class="col-md-2 offset-md-8">
      <button type="button" class="btn btn-purple-secondary" data-bs-toggle="modal" data-bs-target="#csvImportModal">IMPORT</button>
    </div>
    <div class="col-md-2">
      <%= link_to "EXPORT", admin_students_path(format: :csv), class: "btn btn-purple-secondary" %>
    </div>
  </div>
</div>

<%= render "students_table", records: @students %>

<%= render(
        layout: "admin/shared/csv_import_modal",
        locals: {
            title: "Import New Students",
            csv_template_url: "/students.csv",
            csv_import_url: admin_imports_students_path
        }
    ) do %>
    <ul>
      <li>Open the CSV file with excel or your favourite spreadsheet program.</li>
      <li>Delete the sample data and enter your student names and data in the appropriate columns.</li>
      <li>Save the file as a CSV file.</li>
    </ul>
<% end %>
<div>
  Showing <%= @pagy.from %>-<%= @pagy.to %> of <%= @pagy.count %>
</div>
<div>
  <%== pagy_nav(@pagy) %>
</div>

app/views/admin/students/new.html.erb
<div class="m-5 container">
  <%= link_to "Back", admin_students_path %>

  <h2 class="my-4 mr-5">New Student</h2>

  <%= render "form", path: admin_students_url %>
</div>

app/views/admin/students/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_student_path(@student) %> |
<%= link_to 'Back', admin_students_path %>