config/routes.rb
Rails.application.routes.draw do
  # App Paths
  root to: "dashboard#index"

  # GraphQL
  post "/graphql", to: "graphql#execute"
  mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql" if Rails.env.development?

  # Devise Setup
  devise_scope :user do
    get "users/sign_out" => "devise/sessions#destroy"
  end

  devise_for :users, path: "users"

  namespace :admin do
    resources :organizations, only: [:show, :edit, :update]
    resources :admin_users, except: :destroy do
      member do
        patch "activate"
        patch "deactivate"
      end
    end

    resources :volunteers, except: :destroy do
      member do
        patch "activate"
        patch "deactivate"
        post :send_link
      end
    end

    resources :students, except: :destroy do
      member do
        get :activate
        get :deactivate
      end
    end

    resources :tickets, except: :destroy do
      member do
        post :resolve
      end
    end

    resources :surveys, except: :destroy do
      member do
        post :resolve
      end
    end

    match "imports/volunteers", to: "imports#volunteers", via: :post
    match "imports/students", to: "imports#students", via: :post
  end
end

app/controllers/admin/admin_users_controller.rb
module Admin
  class AdminUsersController < ApplicationController
    def index
      @nav = "Admins"
      @total_admin_users = User.where(role: :admin).order(:last_name)
      @pagy, @admin_users = pagy(@total_admin_users)
    end

    def new
      @admin_user = User.new
    end

    def edit
      @admin_user = User.where(role: :admin).find(params[:id])
    end

    def create
      @admin_user = User.new(admin_user_params)
      @admin_user.skip_password_validation = true

      if @admin_user.valid?
        @admin_user.save!
        redirect_to admin_admin_users_url, notice: "Admin was successfully created."
      else
        flash[:alert] = format_errors(@admin_user)
        render :new
      end
    end

    def update
      @admin_user = User.find(params[:id])
      if @admin_user.update(admin_user_params)
        redirect_to admin_admin_users_url, notice: "Admin was successfully updated."
      else
        flash[:alert] = format_errors(@admin_user)
        render :edit
      end
    end

    def activate
      @admin_user = User.where(role: :admin).find(params[:id])
      @admin_user.activate!

      redirect_to admin_admin_users_url, notice: "Admin was successfully activated."
    end

    def deactivate
      @admin_user = User.where(role: :admin).find(params[:id])

      if current_user == @admin_user
        redirect_to admin_admin_users_url, alert: "You can not deactivate your own account."
      else
        @admin_user.deactivate!(deactivator_id: current_user.id)

        redirect_to admin_admin_users_url, notice: "Admin was successfully deactivated."
      end
    end

    def admin_user_params
      params.require(:user)
        .permit(:first_name, :last_name, :email, :phone_number)
        .merge(role: :admin)
    end
  end
end

app/views/admin/admin_users/_admins_table.html.erb
<table id="sortable">
  <thead>
    <tr>
      <th
        id="admins-first-name"
        data-reflex="click->AdminsTable#sort"
        data-column="first_name"
        data-direction="asc"
        scope="col"
        class="hover:cursor-pointer"
      >
        <span>First name</span>
      </th>
      <th
        id="admins-last-name"
        data-reflex="click->AdminsTable#sort"
        data-column="last_name"
        data-direction="asc"
        scope="col"
        class="hover:cursor-pointer"
      >
        <span>Last name</span>
      </th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th
        id="admins-status"
        data-reflex="click->AdminsTable#sort"
        data-column="status"
        data-direction="asc"
        scope="col"
        class="hover:cursor-pointer"
      >Status</th>
      <th class="text-center" scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% records.each do |admin_user| %>
      <tr scope="row">
        <td>
          <%= admin_user.first_name %>
        </td>
        <td>
          <%= admin_user.last_name %>
        </td>
        <td>
          <%= admin_user.email %>
        </td>
        <td>
          <%= admin_user.phone_number %>
        </td>
        <td>
          <%= admin_user.status %>
        </td>
        <td class="text-center text-teal">
          <%= link_to "Edit", edit_admin_admin_user_path(admin_user) %> |

          <% if admin_user.active? %>
            <%= link_to "Deactivate", deactivate_admin_admin_user_path(admin_user),
                method: :patch,
                data: {
                  confirm_swal: "Are you sure?",
                  confirm_text: "DEACTIVATE",
                  text: "This action will deactivate this admin. Are you sure you want to proceed with deactivation?"
                }
             %>
          <% else %>
            <%= link_to "Activate", activate_admin_admin_user_path(admin_user),
                method: :patch,
                data: {
                  confirm_swal: "Are you sure?",
                  confirm_text: "ACTIVATE",
                  text: "This action will activate this admin. Are you sure you want to proceed with activation?"
                }
            %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/admin_users/_form.html.erb
<%= form_with(model: @admin_user, url: path) do |form| %>
  <div class="row pr-3 pb-4">
    <div class="col-4">
      <%= form.text_field :first_name, class: "form-control", placeholder: "First Name" %>
    </div>
  </div>

  <div class="row pr-3 pb-4">
    <div class="col-4">
      <%= form.text_field :last_name, class: "form-control", placeholder: "Last Name" %>
    </div>
  </div>

  <div class="row pr-3 pb-4">
    <div class="col-4">
      <%= form.text_field :email, class: "form-control", placeholder: "Email" %>
    </div>
  </div>

  <div class="row pr-3 pb-4">
    <div class="col-4">
      <%= form.text_field :phone_number, class: "form-control", placeholder: "Phone Number" %>
    </div>
  </div>

  <div class="row pr-3 pb-4">
    <div class="col-1">
      <%= form.submit "Submit", class: "btn btn-secondary" %>
    </div>
    <div class="col-4">
      <% if @admin_user.persisted? %>
        <% if @admin_user.active? %>
          <td>
            <%= link_to "Deactivate", deactivate_admin_admin_user_path(@admin_user),
                class: "btn btn-secondary",
                method: :patch,
                data: {
                  confirm_swal: "Are you sure?",
                  confirm_text: "DEACTIVATE",
                  text: "This action will deactivate this admin. Are you sure you want to proceed with deactivation?"
                }
             %>
          </td>
        <% else %>
          <td>
            <%= link_to "Activate", deactivate_admin_admin_user_path(@admin_user),
                class: "btn btn-secondary",
                method: :patch,
                data: {
                  confirm_swal: "Are you sure?",
                  confirm_text: "ACTIVATE",
                  text: "This action will activate this admin. Are you sure you want to proceed with activation?"
                }
             %>
          </td>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/admin/admin_users/edit.html.erb
<div class="m-5 container">
  <%= link_to "Back", admin_admin_users_path %>

  <h2 class="my-4 mr-5">Edit Admin</h2>

  <%= render "form", path: admin_admin_user_url %>
</div>

app/views/admin/admin_users/index.html.erb
<% content_for(:title) do %>
  Admins
<% end %>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-2">
      <h1><%= page_header_title %></h1>
    </div>
    <div class="col-2 offset-8">
      <%= link_to "ADD NEW", new_admin_admin_user_path, class: "btn btn-purple-primary"  %>
    </div>
  </div>

  <div class="row mt-3 py-3"></div>
</div>

<%= render "admins_table", records: @admin_users %>
<div>
  Showing <%= @pagy.from %>-<%= @pagy.to %> of <%= @pagy.count %>
</div>
<div>
  <%== pagy_nav(@pagy) %>
</div>

app/views/admin/admin_users/new.html.erb
<div class="m-5 container">
  <%= link_to "Back", admin_admin_users_path %>

  <h2 class="my-4 mr-5">New Admin</h2>

  <%= render "form", path: admin_admin_users_url %>
</div>