config/routes.rb
Rails.application.routes.draw do
  # App Paths
  root to: "dashboard#index"

  # GraphQL
  post "/graphql", to: "graphql#execute"
  mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql" if Rails.env.development?

  # Devise Setup
  devise_scope :user do
    get "users/sign_out" => "devise/sessions#destroy"
  end

  devise_for :users, path: "users"

  namespace :admin do
    resources :organizations, only: [:show, :edit, :update]
    resources :admin_users, except: :destroy do
      member do
        patch "activate"
        patch "deactivate"
      end
    end

    resources :volunteers, except: :destroy do
      member do
        patch "activate"
        patch "deactivate"
        post :send_link
      end
    end

    resources :students, except: :destroy do
      member do
        get :activate
        get :deactivate
      end
    end

    resources :tickets, except: :destroy do
      member do
        post :resolve
      end
    end

    resources :surveys, except: :destroy do
      member do
        post :resolve
      end
    end

    match "imports/volunteers", to: "imports#volunteers", via: :post
    match "imports/students", to: "imports#students", via: :post
  end
end

app/controllers/admin/volunteers_controller.rb
module Admin
  class VolunteersController < ApplicationController
    def index
      @nav = "Volunteers"
      @total_volunteers = User.where(role: :volunteer).order(:last_name)
      @pagy, @volunteers = pagy(@total_volunteers)

      session[:filters] = {volunteers_table: {}} unless @stimulus_reflex

      respond_to do |format|
        format.html
        format.csv do
          send_data(
            User.export_to_csv(@total_volunteers,
              columns: User::VOLUNTEER_EXPORT_COLUMNS,
              headers: User::VOLUNTEER_EXPORT_HEADERS),
            filename: "volunteers-#{Date.current}.csv"
          )
        end
      end
    end

    def new
      @volunteer = User.new
    end

    def edit
      @volunteer = User.find(params[:id])
    end

    def create
      @volunteer = User.new(volunteer_params)
      @volunteer.skip_password_validation = true

      if @volunteer.valid?
        @volunteer.save!
        redirect_to admin_volunteers_url, notice: "Volunteer was successfully created."
      else
        flash[:alert] = format_errors(@volunteer)
        render :new
      end
    end

    def update
      @volunteer = User.find(params[:id])
      if @volunteer.update(volunteer_params)
        redirect_to admin_volunteers_url, notice: "Volunteer was successfully updated."
      else
        flash[:alert] = format_errors(@volunteer)
        render :edit
      end
    end

    def activate
      @volunteer = User.find(params[:id])
      @volunteer.activate!

      redirect_to admin_volunteers_url, alert: "Volunteer was successfully activated."
    end

    def deactivate
      @volunteer = User.find(params[:id])
      @volunteer.deactivate!(deactivator_id: current_user.id)

      redirect_to admin_volunteers_url, alert: "Volunteer was successfully deactivated."
    end

    def send_link
      volunteer = User.find(params[:id])

      MagicLinkMailer.sign_in(volunteer).deliver

      flash[:alert] = "Authentication link sent to #{volunteer.name}"
      redirect_to action: :index
    end

    private

    def volunteer_params
      params.require(:user).permit(:first_name, :last_name, :email, :phone_number)
    end
  end
end

app/views/admin/volunteers/_form.html.erb
<%= form_with(model: @volunteer, url: path) do |form| %>

  <div class="row pr-3 pb-4">
    <div class="col-4">
      <%= form.text_field :first_name, class: "form-control", placeholder: "First Name" %>
    </div>
  </div>

  <div class="row pr-3 pb-4">
    <div class="col-4">
      <%= form.text_field :last_name, class: "form-control", placeholder: "Last Name" %>
    </div>
  </div>

  <div class="row pr-3 pb-4">
    <div class="col-4">
      <%= form.text_field :email, class: "form-control", placeholder: "Email" %>
    </div>
  </div>

  <div class="row pr-3 pb-4">
    <div class="col-4">
      <%= form.text_field :phone_number, class: "form-control", placeholder: "Phone Number" %>
    </div>
  </div>

  <div class="row pr-3 pb-4">
    <div class="col-1">
      <%= form.submit "Submit", class: "btn btn-secondary" %>
    </div>
    <div class="col-4">
      <% if @volunteer.persisted? %>
        <% if @volunteer.active? %>
          <%= link_to "Deactivate", deactivate_admin_volunteer_path(@volunteer),
                class: "btn btn-secondary",
                method: :patch,
                data: {
                  confirm_swal: "Are you sure?",
                  confirm_text: "DEACTIVATE",
                  text: "This action will deactivate this volunteer. Are you sure you want to proceed with deactivation?"
                }
             %>
          <% else %>
            <%= link_to "Activate", activate_admin_volunteer_path(@volunteer),
                class: "btn btn-secondary",
                method: :patch,
                data: {
                  confirm_swal: "Are you sure?",
                  confirm_text: "ACTIVATE",
                  text: "This action will activate this volunteer. Are you sure you want to proceed with activation?"
                }
            %>
        <% end %>
      <% end %>
    </div>
  </div>

<% end %>

app/views/admin/volunteers/_volunteers_table.html.erb
<table id="sortable">
  <thead>
    <tr>
      <th
        id="volunteers-first-name"
        data-reflex="click->VolunteersTable#sort"
        data-column="first_name"
        data-direction="asc"
        scope="col"
        class="hover:cursor-pointer"
      >
        <span>First name</span>
      </th>
      <th
        id="volunteers-last-name"
        data-reflex="click->VolunteersTable#sort"
        data-column="last_name"
        data-direction="asc"
        scope="col"
        class="hover:cursor-pointer"
      >
        <span>Last name</span>
      </th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Staff Contact</th>
      <th scope="col">Students</th>
      <th
        id="volunteers-status"
        data-reflex="click->VolunteersTable#sort"
        data-column="status"
        data-direction="asc"
        scope="col"
        class="hover:cursor-pointer"
      >
        <span>Status</span>
      </th>
      <th class="text-center" scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <tr scope="row">
      <td>
        <input
          type="text"
          name="first_name"
          data-reflex="input->VolunteersTable#filter"
          data-column="first_name"
          value="<%= session.dig(:filters, :volunteers_table, 'first_name') %>"
          class="form-control">
      </td>
      <td>
        <input
          type="text"
          name="last_name"
          data-reflex="input->VolunteersTable#filter"
          data-column="last_name"
          value="<%= session.dig(:filters, :volunteers_table, 'last_name') %>"
          class="form-control">
      </td>
      <td>
      </td>
      <td>
      </td>
      <td>
        <input
          type="text"
          name="staff_names"
          data-reflex="input->VolunteersTable#filter"
          data-column="staff_names"
          value="<%= session.dig(:filters, :volunteers_table, 'staff_names') %>"
          class="form-control">
      </td>
      <td>
      </td>
      <td>
        <select
          name="status"
          class="form-select"
          data-column="status"
          data-reflex="change->VolunteersTable#filter">
          <option value='' <%= 'selected' if !session.dig(:filters, :volunteers_table, 'status') %>></option>

          <% User.statuses.each do |k, v| %>
            <option value=<%= v %> <%= 'selected' if v.to_s == session.dig(:filters, :volunteers_table, 'status') %>><%= k %></option>
          <% end %>
        </select>
      </td>
      <td class="text-center text-teal">
      </td>
    </tr>
    <% records.each do |volunteer| %>
      <tr scope="row">
        <td>
          <%= volunteer.first_name %>
        </td>
        <td>
          <%= volunteer.last_name %>
        </td>
        <td class="nowrap">
          <%= volunteer.email %>
        </td>
        <td class="nowrap">
          <%= format_phone_number(volunteer.phone_number) %>
        </td>
        <td>
          <%= volunteer.staff_names %>
        </td>
        <td>
          <%= volunteer.student_names %>
        </td>
        <td>
          <%= volunteer.status %>
        </td>
        <td class="text-center text-teal">
          <%= link_to "Edit", edit_admin_volunteer_path(volunteer) %> |
          <%= link_to "Send Link", send_link_admin_volunteer_path(volunteer), method: :post %> |

          <% if volunteer.active? %>
            <%= link_to "Deactivate", deactivate_admin_volunteer_path(volunteer),
                method: :patch,
                data: {
                  confirm_swal: "Are you sure?",
                  confirm_text: "DEACTIVATE",
                  text: "This action will deactivate this volunteer. Are you sure you want to proceed with deactivation?"
                }
             %>
          <% else %>
            <%= link_to "Activate", activate_admin_volunteer_path(volunteer),
                method: :patch,
                data: {
                  confirm_swal: "Are you sure?",
                  confirm_text: "ACTIVATE",
                  text: "This action will activate this volunteer. Are you sure you want to proceed with activation?"
                }
            %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/volunteers/edit.html.erb
<div class="m-5 container">
  <%= link_to "Back", admin_volunteers_path %>

  <h2 class="my-4 mr-5">Edit Volunteer</h2>

  <%= render "form", path: admin_volunteer_url %>
</div>

app/views/admin/volunteers/index.html.erb
<% content_for(:title) do %>
  Volunteers
<% end %>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-2">
      <h1><%= page_header_title %></h1>
    </div>
    <div class="col-md-2 offset-md-8">
      <%= link_to "ADD NEW", new_admin_volunteer_path, class: "btn btn-purple-primary"  %>
    </div>
  </div>

  <div class="row bg-white py-3 mt-3">
    <div class="col-md-2 offset-md-8">
      <button type="button" class="btn btn-purple-secondary" data-bs-toggle="modal" data-bs-target="#csvImportModal">IMPORT</button>
    </div>
    <div class="col-md-2">
      <%= link_to "EXPORT", admin_volunteers_path(format: :csv), class: "btn btn-purple-secondary" %>
    </div>
  </div>
</div>

<%= render "volunteers_table", records: @volunteers %>

<%= render(
        layout: "admin/shared/csv_import_modal",
        locals: {
            title: "Import New Volunteers",
            csv_template_url: "/volunteers.csv",
            csv_import_url: admin_imports_volunteers_path
        }
    ) do %>
    <ul>
      <li>Open the CSV file with excel or your favourite spreadsheet program.</li>
      <li>Delete the sample data and enter you partner agency names and addresses in the appropriate columns.</li>
      <li>Save the file as a CSV file.</li>
    </ul>
<% end %>
<div>
  Showing <%= @pagy.from %>-<%= @pagy.to %> of <%= @pagy.count %>
</div>
<div>
  <%== pagy_nav(@pagy) %>
</div>

app/views/admin/volunteers/new.html.erb
<div class="m-5 container">
  <%= link_to "Back", admin_volunteers_path %>

  <h2 class="my-4 mr-5">New Volunteer</h2>

  <%= render "form", path: admin_volunteers_url %>
</div>

app/views/admin/volunteers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_volunteer_path(@admin_volunteer) %> |
<%= link_to 'Back', admin_volunteers_path %>