config/routes.rb
Rails.application.routes.draw do
  # App Paths
  root to: "dashboard#index"

  # GraphQL
  post "/graphql", to: "graphql#execute"
  mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql" if Rails.env.development?

  # Devise Setup
  devise_scope :user do
    get "users/sign_out" => "devise/sessions#destroy"
  end

  devise_for :users, path: "users"

  namespace :admin do
    resources :organizations, only: [:show, :edit, :update]
    resources :admin_users, except: :destroy do
      member do
        patch "activate"
        patch "deactivate"
      end
    end

    resources :volunteers, except: :destroy do
      member do
        patch "activate"
        patch "deactivate"
        post :send_link
      end
    end

    resources :students, except: :destroy do
      member do
        get :activate
        get :deactivate
      end
    end

    resources :tickets, except: :destroy do
      member do
        post :resolve
      end
    end

    resources :surveys, except: :destroy do
      member do
        post :resolve
      end
    end

    match "imports/volunteers", to: "imports#volunteers", via: :post
    match "imports/students", to: "imports#students", via: :post
  end
end

app/controllers/admin/tickets_controller.rb
module Admin
  class TicketsController < ApplicationController
    before_action :ticket, only: %i[show resolve]

    def index
      @nav = "Tickets"
      @total_tickets = SupportTicket.order(:created_at)
      @pagy, @tickets = pagy(@total_tickets)

      respond_to do |format|
        format.html
        format.csv do
          columns = %w[requestor.name created_at survey_response_id survey_response.student.name
            survey_response.student.active_student_staff_assignment.staff.name display_category display_status ]
          headers = ["Requested By", "Date Created", "Response ID", "Student", "Staff Contact", "Type", "Status"]

          send_data SupportTicket.export_to_csv(@tickets, columns: columns, headers: headers),
            filename: "support-tickets-#{Date.today}.csv"
        end
      end
    end

    def new
      @ticket = SupportTicket.new
    end

    def create
      @ticket = SupportTicket.new(ticket_params)
      @ticket.category = :admin

      if @ticket.valid?
        @ticket.save!
        redirect_to admin_tickets_url, notice: "Support ticket was successfully created."
      else
        flash[:alert] = format_errors(@ticket)
        render :new
      end
    end

    def show
    end

    def resolve
      if ticket.close!(current_user, ticket_update_params[:closer_notes])
        redirect_to admin_tickets_path, notice: "The support ticket was successfully resolved."
      else
        flash[:alert] = "Could not resolve the support ticket. Please try again."
        render :show
      end
    end

    private

    def ticket_params
      params.require(:support_ticket).permit(:requestor_id, :description)
    end

    def ticket_update_params
      params.require(:support_ticket).permit(:closer_notes)
    end

    def ticket
      return @ticket if defined?(@ticket)

      @ticket = SupportTicket.find(params[:id])
    end
  end
end

app/views/admin/tickets/_tickets_table.html.erb
<table id="sortable">
  <thead>
    <tr>
      <th id="tickets-requested_by"
          data-reflex="click->TicketsTable#sort"
          data-column="users.first_name"
          data-direction="asc"
          scope="col"
          class="hover:cursor-pointer">
        <span>Requested By</span>
      </th>
      <th id="tickets-date-created"
          data-reflex="click->TicketsTable#sort"
          data-column="created_at"
          data-direction="asc"
          scope="col"
          class="hover:cursor-pointer">
        <span>Date Created</span>
      </th>
      <th scope="col">Response ID</th>
      <th id="tickets-student"
          data-reflex="click->TicketsTable#sort"
          data-column="students.last_name"
          data-direction="asc"
          scope="col"
          class="hover:cursor-pointer">
        <span>Student</span>
      </th>
      <th id="tickets-staff-contact"
          data-reflex="click->TicketsTable#sort"
          data-column="staffs_student_staff_assignments.last_name"
          data-direction="asc"
          scope="col"
          class="hover:cursor-pointer">
        <span>Staff Contact</span>
      </th>
      <th id="tickets-type"
          data-reflex="click->TicketsTable#sort"
          data-column="category"
          data-direction="asc"
          scope="col"
          class="hover:cursor-pointer">
        <span>Type</span>
      </th>
      <th class="text-center" scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% records.each do |ticket| %>
      <tr scope="row">
        <td>
          <%= ticket.requestor.name %>
        </td>
        <td>
          <%= ticket.created_at.strftime('%m/%d/%Y') %>
        </td>
        <td>
          <%= ticket.survey_response_id %>
        </td>
        <td>
          <%= ticket.student_name %>
        </td>
        <td>
          <%= ticket.staff_contact_name %>
        </td>
        <td>
          <%= ticket.display_category %>
        </td>
        <td class="text-center text-teal">
          <%= link_to(ticket.display_status, admin_ticket_path(ticket)) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/tickets/index.html.erb
<% content_for(:title) do %>
  Support Tickets
<% end %>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-4">
      <h1><%= page_header_title %></h1>
    </div>
    <div class="col-md-2 offset-md-6">
      <%= link_to "ADD NEW", new_admin_ticket_path, class: "btn btn-purple-primary" %>
    </div>
  </div>

  <div class="row bg-white py-3 mt-3">
    <div class="col-md-2 offset-md-10">
      <%= link_to "EXPORT", admin_tickets_path(format: :csv), class: "btn btn-purple-secondary" %>
    </div>
  </div>
</div>

<%= render "tickets_table", records: @tickets %>
<div>
  Showing <%= @pagy.from %>-<%= @pagy.to %> of <%= @pagy.count %>
</div>
<div>
  <%== pagy_nav(@pagy) %>
</div>

app/views/admin/tickets/new.html.erb
<div class="m-5 container">
  <%= link_to "Back", admin_tickets_path %>

  <h2 class="my-4 mr-5">New Support Ticket</h2>

  <%= form_with(model: @ticket, url: admin_tickets_url) do |form| %>
    <div class="row pr-3 pb-4">
      <div class="col-4">
        <%= form.collection_select :requestor_id, User.all, :id, :name, class: "form-control", prompt: "Please select the requestor" %>
      </div>
    </div>

    <div class="row pr-3 pb-4">
      <div class="col-4">
        <%= form.text_area :description, class: "form-control", placeholder: "Description" %>
      </div>
    </div>

    <div class="row pr-3 pb-4">
      <div class="col-4">
        <%= form.submit "Submit" %>
      </div>
    </div>

  <% end %>
</div>

app/views/admin/tickets/show.html.erb
<div class="container">
  <%= link_to "Back", admin_tickets_path %>

  <div class="pb-2">
    <h2>
      <%= @ticket.requestor.name %>
      <p class="text-dark-gray fs-5"><%= @ticket.display_category %> Request</p>
    </h2>
  </div>

  <div>
    <div class="card shadow-sm">
      <div class="card-body">
        <div class="row">
          <div class="col-3">
            <label class="text-dark-gray">DATE CREATED</label>
            <p><%= @ticket.created_at.to_date.to_formatted_s(:long) %></p>
          </div>
          <div class="col-3">
            <label class="text-dark-gray">CREATED BY</label>
            <p><%= @ticket.requestor.name %></p>
          </div>
          <div class="col-3">
            <label class="text-dark-gray">STUDENT</label>
            <p><%= @ticket.student_name %></p>
          </div>
          <div class="col-3">
            <label class="text-dark-gray">STAFF CONTACT</label>
            <p><%= @ticket.staff_contact_name %></p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <% if @ticket.closer.present? %>
    <div class="pb-4">
      <div class="card shadow-sm">
        <div class="card-body">
          <div class="row">
            <div class="col-3">
              <label class="text-dark-gray">CLOSE DATE</label>
              <p><%= @ticket.closed_at.to_date.to_formatted_s(:long) %></p>
            </div>
            <div class="col-3">
              <label class="text-dark-gray">CLOSED BY</label>
              <p><%= @ticket.closer.name %></p>
            </div>
            <div class="col-3">
              <label class="text-dark-gray">STATUS</label>
              <p><%= @ticket.display_status %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <div class="pb-4">
    <div class="card shadow-sm">
      <div class="card-body">
        <label class="text-dark-gray">DESCRIPTION</label>
        <p class="card-text"><%= @ticket.description %></p>
      </div>
    </div>
  </div>

  <% if @ticket.closer.present? %>
    <div class="pb-2">
      <div class="card shadow-sm">
        <div class="card-body">
          <label class="text-dark-gray">RESOLUTION DESCRIPTION</label>
          <p class="card-text"><%= @ticket.closer_notes %></p>
        </div>
      </div>
    </div>
  <% else %>

    <%= form_with(model: @ticket, url: resolve_admin_ticket_url, method: :post) do |f| %>
      <label class="text-dark-gray mt-4 mb-3">RESOLUTION DESCRIPTION</label>
      <div class="row pr-3 pb-2">
        <div>
          <%= f.text_area :closer_notes, class: "form-control", placeholder: "Describe how support request was resolved" %>
        </div>
      </div>

      <div class="row pr-3 pb-4 mt-4">
        <div class="col-2">
          <%= link_to "CANCEL", admin_tickets_path, class: "btn btn-lg btn-purple-secondary" %>
        </div>
        <div class="col-2">
          <%= f.submit "RESOLVE", class: "btn btn-lg btn-purple-primary" %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>